kind: ConfigMap
apiVersion: v1
metadata:
  name: tsdb-writer
data:
  POSTGRESQL_ENABLED: "true"
  POSTGRESQL_ENDPOINT: "postgres://postgres:password@timescaledb:5432/postgres?sslmode=disable"
  REDIS_STREAMS_ENDPOINT: "redis:6379"
  REDIS_STREAMS_START: "$"
  REDIS_TS_ENABLED: "true"
  REDIS_TS_ENDPOINT: "redis-timeseries:6379"
