kind: Namespace
apiVersion: v1
metadata:
  name: argocd
  labels:
    name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-workflows
  namespace: argocd
spec:
  destination:
    namespace: nfs-provisioner
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/argo-workflows/
    repoURL: https://github.com/jaredmcqueen/lab-automation.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
