kind: Namespace
apiVersion: v1
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: ""
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/cert-manager/
    repoURL: https://github.com/jaredmcqueen/lab-automation.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
