# kind: Namespace
# apiVersion: v1
# metadata:
#   name: nfs-provisioner
#   labels:
#     name: nfs-provisioner
# ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-client
  namespace: argocd
spec:
  destination:
    # namespace: ''
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/nfs-provisioner/
    repoURL: https://github.com/jaredmcqueen/lab-automation.git
    targetRevision: HEAD
