apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/sealed-secrets
    repoURL: https://github.com/jaredmcqueen/lab-automation.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
