- name: clone .dotfiles repo
  git:
    accept_hostkey: true
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    force: true
    recursive: true
    repo: git@github.com:jaredmcqueen/dotfiles.git
    update: true
    version: main
- name: delete .zshrc
  shell: rm -f $HOME/.zshrc
- name: stow dotfiles
  shell: sh $HOME/.dotfiles/stow.sh
