- name: install fonts
  become: yes
  shell: |
    pacman-key --recv-keys 16F249ED243F596E
    pacman-key --lsign-key 16F249ED243F596E
- name: add line in pacman.conf
  become: yes
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [sainnhe]
      Server = https://repo.sainnhe.dev/archlinux/$arch
- name: update yay
  become: yes
  command: yay -Sy
- name: update pacman and install fonts
  kewlfft.aur.aur:
    use: yay
    name:
      - ttf-fira-code-icursive-s12
      - ttf-hack-icursive-s12
      - ttf-inconsolatalgc-icursive-s12
      - ttf-lilex-icursive-s12
      - ttf-meslo-icursive-s12
      - ttf-source-code-pro-icursive-s12
