- name: install i3
  kewlfft.aur.aur:
    name:
      - xorg
      - lightdm
      - lightdm-gtk-greeter
      - rofi
      - picom-ibhagwan-git
      - redshift
      - alternating-layouts-git
      - nerd-fonts-hack
      - i3-wm
      - stow
      - feh
      - lightdm-webkit-theme-aether
      - ranger
      - ueberzug
      - dunst
    use: yay
- name: install python-i3ipc
  pip:
    name: pillow-simd
- name: enable lightdm
  become: true
  shell: "systemctl enable lightdm"
- name: Uncomment line from /etc/lightdm/lightdm.conf
  become: true
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    line: logind-check-graphical=true
    regexp: "^#logind-check-graphical=false$"
- name: patch left pointer cursor
  become: true
  shell: |
    rm /usr/share/icons/Adwaita/cursors/watch
    rm /usr/share/icons/Adwaita/cursors/left_ptr_watch
    sudo ln -s /usr/share/icons/Adwaita/cursors/left_ptr /usr/share/icons/Adwaita/cursors/watch
    sudo ln -s /usr/share/icons/Adwaita/cursors/left_ptr /usr/share/icons/Adwaita/cursors/left_ptr_watch
