- name: install i3
  kewlfft.aur.aur:
    use: yay
    name:
      - xorg
      - lightdm
      - lightdm-gtk-greeter
      - rofi
      - picom-ibhagwan-git
      - redshift
      - alternating-layouts-git
      - nerd-fonts-hack
      - i3-wm
      - stow
      - feh
      - lightdm-webkit-theme-aether
      - ranger
      - ueberzug
      - dunst
- name: install python-i3ipc
  pip:
    name: i3ipc
    name: pillow-simd

- name: enable lightdm
  become: yes
  shell: |
    systemctl enable lightdm

- name: Uncomment line from /etc/lightdm/lightdm.conf
  become: yes
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    regexp: "^#logind-check-graphical=false$"
    line: "logind-check-graphical=true"

- name: patch left pointer cursor
  become: yes
  shell: |
    rm /usr/share/icons/Adwaita/cursors/watch
    rm /usr/share/icons/Adwaita/cursors/left_ptr_watch
    sudo ln -s /usr/share/icons/Adwaita/cursors/left_ptr /usr/share/icons/Adwaita/cursors/watch
    sudo ln -s /usr/share/icons/Adwaita/cursors/left_ptr /usr/share/icons/Adwaita/cursors/left_ptr_watch
