- name: install zsh packages
  kewlfft.aur.aur:
    use: yay
    name:
      - zsh
      - starship
      - oh-my-zsh-git
      - oh-my-zsh-plugin-autosuggestions
      - zsh-syntax-highlighting

- name: change shell to zsh
  shell: sudo chsh -s $(which zsh) $(whoami)
