- name: install zsh packages
  kewlfft.aur.aur:
    name:
      - oh-my-zsh-git
      - oh-my-zsh-plugin-autosuggestions
      - starship
      - zsh
      - zsh-syntax-highlighting
    use: yay
- name: change shell to zsh
  shell: sudo chsh -s $(which zsh) $(whoami)
