kind: ConfigMap
apiVersion: v1
metadata:
  name: quote-writer
data:
  REDIS_ENDPOINT: "redis:6379"
  REDIS_STREAM_START: "0"
  REDIS_STREAM_COUNT: "5000"
  TIMESCALEDB_CONNECTION: "postgres://postgres:password@timescaledb:5432/postgres?sslmode=disable"
  TIMESCALEDB_BATCH_SIZE: "10000"
  TIMESCALEDB_BATCH_TIMEOUT: "250"
  TIMESCALEDB_WORKERS: "4"
