apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-writer
  labels:
    app: quote-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-writer
  template:
    metadata:
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        app: quote-writer
    spec:
      containers:
      - name: quote-writer
        image: ghcr.io/jaredmcqueen/quote-writer:latest
        envFrom:
          - configMapRef:
              name: quote-writer
