kind: ConfigMap
apiVersion: v1
metadata:
  name: alpaca-streaming-receiver
data:
  BASE_URL: https://paper-api.alpaca.markets
  CHANNEL_QUEUE_SIZE: "100000"
  ENABLE_BARS: "true"
  ENABLE_QUOTES: "true"
  ENABLE_STATUSES: "true"
  ENABLE_TRADES: "true"
  REDIS_BATCH_MAX_SIZE: "5000"
  REDIS_BATCH_TIMEOUT: "250"
  REDIS_ENDPOINT: redis:6379
  REDIS_WORKERS: "1"
  SYMBOLS_BARS: '*'
  SYMBOLS_QUOTES: '*'
  SYMBOLS_STATUSES: '*'
  SYMBOLS_TRADES: '*'
