apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-streaming-receiver
  labels:
    app: alpaca-streaming-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpaca-streaming-receiver
  template:
    metadata:
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        app: alpaca-streaming-receiver
    spec:
      containers:
      - name: alpaca-streaming-receiver
        image: ghcr.io/jaredmcqueen/alpaca-streaming-receiver:latest
        envFrom:
          - secretRef:
              name: alpaca-streaming-receiver
          - configMapRef:
              name: alpaca-streaming-receiver
