apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-timeseries-ui
spec:
  ingressClassName: nginx
  rules:
    - host: "redis-timeseries.alphavector.io"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: redis-timeseries-ui
                port:
                  number: 8001
