apiVersion: v1
kind: Service
metadata:
  name: redis-timeseries
spec:
  selector:
    app: redis-timeseries
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-timeseries-ui
spec:
  selector:
    app: redis-timeseries
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
