apiVersion: v1
data:
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL2phcmVkbWNxdWVlbi9sYWItYXV0b21hdGlvbi5naXQ=
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: lab-automation
  namespace: argocd
type: Opaque
