apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: timescaledb
  name: timescaledb
spec:
  replicas: 1
  serviceName: timescaledb
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      # securityContext:
        # runAsUser: 70
        # runAsGroup: 70
        # fsGroup: 70
        # runAsNonRoot: true
      containers:
        - name: timescaledb
          # image: timescale/timescaledb:latest-pg14
          image: timescale/timescaledb-ha:pg14-latest
          # image: timescale/timescaledb:latest-pg14-bitnami
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "postgres"
            - name: PGDATA
              value: "/data"
          volumeMounts:
            - mountPath: /data
              name: tsdb-data
  volumeClaimTemplates:
    - metadata:
        name: tsdb-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
