apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-streams-timeseries
  labels:
    app: redis-streams-timeseries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-streams-timeseries
  template:
    metadata:
      labels:
        app: redis-streams-timeseries
    spec:
      containers:
      - name: redis-streams-timeseries
        image: ghcr.io/jaredmcqueen/redis-streams-timeseries:latest
        envFrom:
          - configMapRef:
              name: redis-streams-timeseries
