- name: set hostnames
  tags: common
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"
- name: stop ufw service
  tags: common
  become: yes
  service:
    name: ufw
    state: stopped
- name: overlay kernel module
  tags: common
  become: yes
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: overlay
- name: br_netfilter kernel module
  tags: common
  become: yes
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: br_netfilter
- name: modprobe overlay and br_netfilter
  tags: common
  become: yes
  shell: |
    modprobe overlay
    modprobe br_netfilter
- name: bridge-nf-call-ip6tables
  tags: common
  become: yes
  lineinfile:
    path: /etc/sysctl.d/kubernetes.conf
    line: net.bridge.bridge-nf-call-ip6tables = 1
    create: yes
- name: bridge-nf-call-iptables
  tags: common
  become: yes
  lineinfile:
    path: /etc/sysctl.d/kubernetes.conf
    line: net.bridge.bridge-nf-call-iptables = 1
    create: yes
- name: ip_forward
  tags: common
  become: yes
  lineinfile:
    path: /etc/sysctl.d/kubernetes.conf
    line: net.ipv4.ip_forward = 1
    create: yes
- name: set up ip forwarding
  tags: common
  become: yes
  shell: |
    sysctl --system >/dev/null 2>&1
- name: install containerd
  tags: common
  become: yes
  apt:
    pkg:
      - containerd
      - apt-transport-https
    update_cache: yes
- name: create containerd defaults
  tags: common
  become: yes
  shell: |
    mkdir /etc/containerd
    containerd config default > /etc/containerd/config.toml
- name: restart containerd
  tags: common
  become: yes
  service:
    name: containerd
    state: restarted
- name: add k8s repo gpg key
  tags: common
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: add k8s repo
  tags: common
  become: yes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
- name: install kubernetes components
  tags: common
  become: yes
  apt:
    pkg:
      - kubeadm
      - kubelet
      - kubectl
      - nfs-common
    update_cache: yes
- name: add inventory to hosts file
  tags: common
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ item }}$"
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
