all: # keys must be unique, i.e. only one 'hosts' per group
  children:
    controllers:
      hosts:
        dev-controller:
          ansible_host: 10.0.6.41
    workers:
      hosts:
        dev-worker1:
          ansible_host: 10.0.6.42
        dev-worker2:
          ansible_host: 10.0.6.43
        dev-worker3:
          ansible_host: 10.0.6.44
