all: # keys must be unique, i.e. only one 'hosts' per group
  children:
    controller:
      hosts:
        controller:
          ansible_host: 10.0.6.31
    # workers:
    #   hosts:
    #     worker1:
    #       ansible_host: 10.0.6.72
    #     worker2:
    #       ansible_host: 10.0.6.73
