all: # keys must be unique, i.e. only one 'hosts' per group
  children:
    controller:
      hosts:
        controller:
          ansible_host: 10.0.6.31
      vars:
        ansible_user: ubuntu
    workers:
      hosts:
        worker-1:
          ansible_host: 10.0.6.32
        worker-2:
          ansible_host: 10.0.6.33
      vars:
        ansible_user: ubuntu
