- hosts: all
  tasks:
    - include_tasks: common.yaml
      tags: common
- hosts: controller
  tasks:
    - include_tasks: controller.yaml
      tags: controller
- hosts: workers
  tasks:
    - include_tasks: worker.yaml
      tags: workers
- hosts: controller
  tags: services
  vars:
    metallb_start: 10.0.6.20
    metallb_end: 10.0.6.29
  tasks:
    - include_tasks: services.yaml
