- hosts: all
  tasks:
    - include_tasks: common.yaml
      tags: common
- hosts: controller
  tasks:
    - include_tasks: controller.yaml
      tags: controller
- hosts: workers
  tasks:
    - include_tasks: worker.yaml
      tags: workers
- hosts: controller
  tasks:
    - include_tasks: services.yaml
      tags: services
