- name: create metallb-system namespace
  tags: services
  become: yes
  kubernetes.core.k8s:
    name: metallb-system
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
- name: create argocd namespace
  tags: services
  become: yes
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
- name: download argocd manifest
  tags: services
  become: yes
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    dest: ~/argo-install.yaml
- name: install argocd
  tags: services
  become: yes
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    namespace: argocd
    src: ~/argo-install.yaml
