apiVersion: apps/v1
kind: Deployment
metadata:
  name: tick-generator
  labels:
    app: tick-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tick-generator
  template:
    metadata:
      labels:
        app: tick-generator
    spec:
      containers:
        - name: tick-generator
          image: ghcr.io/jaredmcqueen/tick-generator:latest
