apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-debug
spec:
  containers:
    - image: ubuntu
      command:
        - "sleep"
        - "604800"
      imagePullPolicy: IfNotPresent
      name: ubuntu
