apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  destination:
    namespace: traefik
    server: 'https://kubernetes.default.svc'
  source:
    path: traefik
    repoURL: 'https://github.com/jaredmcqueen/k8s-deployments.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
