apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: jaredmcqueen@gmail.com
    privateKeySecretRef:
      name: my-cloudflare-key-staging
    solvers:
      - dns01:
          cloudflare:
            email: jaredmcqueen@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
