- name: install apps
  kewlfft.aur.aur:
    name:
      - ccid
      - opensc
      - pcsc-tools
      - coolkey
    use: yay
- name: start and enable pcscd
  become: yes
  ignore_errors: true
  service:
    name: pcscd
    state: started
    enabled: true
- name: download and install certs
  ignore_errors: true
  shell: |
    curl https://militarycac.com/maccerts/AllCerts.p7b --output /tmp/certs.p7b
    openssl pkcs7 -inform DER -outform PEM -in /tmp/certs.p7b -print_certs > /tmp/certificate_bundle.cer
- name: add to trust anchor
  become: true
  ignore_errors: true
  shell: |
    killall -q brave
    killall -q chrome
    killall -q firefox
    trust anchor --store /tmp/certificate_bundle.cer
- name: add CAC Module
  ignore_errors: true
  shell: 'modutil -force -dbdir sql:$HOME/.pki/nssdb/ -add "CAC Module" -libfile /usr/lib/opensc-pkcs11.so'
