- name: install fonts
  become: yes
  shell: |
    pacman-key --recv-keys 16F249ED243F596E
    pacman-key --lsign-key 16F249ED243F596E
- name: add line in pacman.conf
  become: yes
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [sainnhe]
      Server = https://repo.sainnhe.dev/archlinux/$arch
- name: update yay
  become: yes
  command: yay -Sy
- name: install special fonts
  kewlfft.aur.aur:
    use: yay
    name:
      - ttf-hack-icursive-s12
      - otf-font-awesome
      - nerd-fonts-terminus # for terminal glyphs
      - noto-fonts-emoji    # for emojis
