- hosts: localhost
  vars:
    priv_key_src: "./ssh/id_rsa"
    priv_key_dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    pub_key_src: "./ssh/id_rsa.pub"
    pub_key_dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  tasks:
    - include: tasks/apps.yaml
      tags: apps
    - include: tasks/ssh.yaml
      tags: ssh
    - include: tasks/i3.yaml
      tags: i3
    - include: tasks/zsh.yaml
      tags: zsh
    - include: tasks/neovim.yaml
      tags: neovim
    - include: tasks/dotfiles.yaml
      tags: dotfiles
    - include: tasks/cac.yaml
      tags: cac
