- hosts: localhost
  vars:
    priv_key_src: "./.ssh/id_rsa"
    priv_key_dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    pub_key_src: "./.ssh/id_rsa.pub"
    pub_key_dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  tasks:
    - include: tasks/apps.yaml
    - include: tasks/ssh.yaml
    - include: tasks/i3.yaml
    - include: tasks/zsh.yaml
    - include: tasks/neovim.yaml
    - include: tasks/dotfiles.yaml
    - include: tasks/cac.yaml
