- hosts: localhost
  tasks:
    - name: create Projects
      file:
        path: /home/jared/Projects
        state: directory
    - name: create Documents
      file:
        path: /home/jared/Documents
        state: directory
    - import_tasks: ssh.yaml
      tags: ssh
    - import_tasks: apps.yaml
      tags: apps
    - import_tasks: i3.yaml
      tags: i3
    - import_tasks: zsh.yaml
      tags: zsh
    - import_tasks: neovim.yaml
      tags: neovim
    - import_tasks: tmux.yaml
      tags: tmux
    - import_tasks: dotfiles.yaml
      tags: dotfiles
    - import_tasks: cac.yaml
      tags: cac
    - import_tasks: fonts.yaml
      tags: fonts
  vars:
    priv_key_dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    priv_key_src: ./ssh/id_rsa
    pub_key_dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
    pub_key_src: ./ssh/id_rsa.pub
