- hosts: localhost
  tasks:
    - import_tasks: tasks/apps.yaml
      tags: apps
    - import_tasks: tasks/i3.yaml
      tags: i3
    - import_tasks: tasks/zsh.yaml
      tags: zsh
    - import_tasks: tasks/neovim.yaml
      tags: neovim
    - import_tasks: tasks/dotfiles.yaml
      tags: dotfiles
    - import_tasks: tasks/cac.yaml
      tags: cac
    - import_tasks: tasks/fonts.yaml
      tags: fonts
  vars:
    priv_key_dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    priv_key_src: ./ssh/id_rsa
    pub_key_dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
    pub_key_src: ./ssh/id_rsa.pub
