argo-workflows:
  workflow:
    serviceAccount:
      create: true
    rbac:
      create: true
  controller:
    metricsConfig:
      enabled: true
    telemetryConfig:
      enabled: true
    serviceMonitor:
      enabled: true
    containerRuntimeExecutor: pns
